src/objects/CallOut__c.object
<CustomObject>
    <fields>
        <fullName>Authorization__c</fullName>
        <label>Authorization</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>EndTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request2__c</fullName>
        <label>Request2</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response2__c</fullName>
        <label>Response2</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>StartTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>--none--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>--none--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CallOut</label>
    <nameField>
        <displayFormat>CA{000000000}</displayFormat>
        <label>CallOut Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CallOuts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SM005_Logs.cls
public class SM005_Logs 
{
    public static list<CallOut__c>lLog = new list<CallOut__c> ();
            public static CallOut__c LogCallOut(string recordId,string callType, string reqBody, string respBody, datetime dtBeg, datetime dtEnd,string sErrorMessage,string sURL, string sAuth)
        {
            return LogCallOut(recordId,callType, reqBody, respBody, dtBeg, dtEnd, sErrorMessage, sURL,sAuth,null,null);
        }
        public static CallOut__c LogCallOut(string recordId,string callType, string reqBody, string respBody, datetime dtBeg, datetime dtEnd,string sErrorMessage)
        {
            return LogCallOut(recordId,callType, reqBody, respBody, dtBeg, dtEnd, sErrorMessage, null,null,null,null);
        }
    public static CallOut__c LogCallOut(string recordId,string callType, string reqBody, string respBody, datetime dtBeg, datetime dtEnd,string sErrorMessage,string sURL, string sAuth,string reqBody2)
    {
        return LogCallOut(recordId,callType, reqBody, respBody, dtBeg, dtEnd, sErrorMessage, sURL,sAuth,reqBody2,null);
    }
    /**
 * @author: SEV@3cconsult.dk
 * @date: 2016-11-21
 * @param: recordId - associated record id or empty string,callType - callout type, reqBody - request body, respBody - response body, dtBeg - begin datetime, dtEnd - end date time, sErrorMessage - error message or empty string
 * @functionality: that method creates callout__c record for web service callouts
 * @bizpurpose: ---
 * @changelog: ---
 * @return: ---
 * */
    
    public static CallOut__c LogCallOut(string recordId,string callType, string reqBody, string respBody, datetime dtBeg, datetime dtEnd,string sErrorMessage,string sURL, string sAuth,string reqBody2, string respBody2)
    {
        CallOut__c c = new CallOut__c();
        if(dtBeg != null && dtEnd != null)
        {
            c.StartTime__c = dtBeg;
            c.EndTime__c = dtEnd;
            c.Duration__c = (dtEnd.getTime() - dtBeg.getTime());
        }
        c.Record_Id__c  = recordId;
        c.Type__c = callType;
        if(reqBody != null && reqBody.length()>131050)
            reqBody = reqBody.substring(0,131050);

        c.Request__c =reqBody;
        if(reqBody2 != null && reqBody2.length()>131050)
            reqBody2 = reqBody2.substring(0,131050);
         c.Request2__c =reqBody2;       
        if(sErrorMessage != null && sErrorMessage.length()>254)
            sErrorMessage = sErrorMessage.substring(0, 253);
        if(sErrorMessage != null && sErrorMessage != '')
            c.Status__c = 'Error'; 
        else
            c.Status__c = 'Success';                 
        c.ErrorMessage__c = sErrorMessage;         
        
        if(respBody != null && respBody.length()>131050)
            respBody = respBody.substring(0,131050);
        c.Response__c = respBody;
        if(respBody2 != null && respBody2.length()>131050)
            respBody2 = respBody2.substring(0,131050);
        c.Response2__c = respBody2;
        if(sURL != null && sURL.length()>255)
            sURL = sURL.substring(255);
        c.URL__c = sURL;
        c.Authorization__c = sAuth;

        
		add(c);
        return c;
//        insert  c;       
    }
    
    
    public static void add(CallOut__c c)
    {
        lLog.add(c);
    }
    
    public static void save()
    {
        if(!lLog.isEmpty())
        {
            insert lLog;
            lLog =  new list<CallOut__c> ();
        }
    }
    
}