src/objects/Ruffle_Draw__c.object
<CustomObject>
    <fields>
        <fullName>Draw_Date__c</fullName>
        <label>Draw Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Winners__c</fullName>
        <label>Number of Winers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Raffle Draw</label>
    <nameField>
        <label>Ruffle Draw Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ruffle Draws</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ruffle_Draw_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Ruffle_Draw__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Raffle Draw</label>
        <referenceTo>Ruffle_Draw__c</referenceTo>
        <relationshipLabel>Ruffle Draw Ticket (Ruffle Draw)</relationshipLabel>
        <relationshipName>Ruffle_Draw_Ticket</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Raffle Draw Ticket</label>
    <nameField>
        <displayFormat>RDT-{0000000000}</displayFormat>
        <label>Ruffle Draw Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ruffle Draw Ticket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RuffleDrawTests.cls
/**
 * Author:         serhiivolynets
 * Date:           31.01.2021
 * Description:
 **/
@IsTest
public class RuffleDrawTests
{
	@TestSetup
	public static void prepareData()
	{
		Ruffle_Draw__c draw = new Ruffle_Draw__c();
		draw.Name = 'aaaa';
		draw.Draw_Date__c = Datetime.now();
		draw.Winners__c = 50;
		insert draw;
		list<Ruffle_Draw_Ticket__c> lTick = new list<Ruffle_Draw_Ticket__c>();
		for (Integer i = 0; i < 100; i++)
		{
			Ruffle_Draw_Ticket__c tick = new Ruffle_Draw_Ticket__c();
			tick.Ruffle_Draw__c = draw.Id;
			lTick.add(tick);
		}
		insert lTick;
	}

	@IsTest
	public static void testIt()
	{
		Test.startTest();
		ApexPages.StandardController ctr = new ApexPages.StandardController([
				select id
				from Ruffle_Draw__c
				limit 1
		]);
		SM082_RuffleDraw draw = new SM082_RuffleDraw(ctr);
		draw.onRun();
		Test.stopTest();
	}

	@IsTest
	public static void testBatch2()
	{
		Ruffle_Draw__c r = [
				select id
				from Ruffle_Draw__c
				limit 1
		];
		Test.startTest();
		Database.executeBatch(new SM082_RaffleDrawBatch(r.Id));
		Test.stopTest();
	}


	@IsTest
	public static void testIt2()
	{
		Test.startTest();
		System.schedule('job1', '0 0 10 * * ?', new SM085_ruffleDrawBatch());
		Test.stopTest();
	}

	@IsTest
	public static void testIt3()
	{

		TestDataFactory data1 = new TestDataFactory();
		SM084_RuffleDrawTicket.TicketInput mess = new SM084_RuffleDrawTicket.TicketInput();
		mess.visitorId = data1.vis.id;
		mess.ticketDate = Date.today();
		Test.startTest();
		SM084_RuffleDrawTicket.getTicket(new list<SM084_RuffleDrawTicket.TicketInput>
		{
				mess
		}
		);
		Test.stopTest();
	}

	@IsTest
	public static void testIt4()
	{
		Test.startTest();
		RestRequest req = new RestRequest();
		req.requestBody = Blob.valueof('{"raffleDrawName":"aaaa"}"');
		RestResponse res = new RestResponse();
		req.requestURI = '/services/apexrest/raffleDraw/';
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;
		SM087_runDraw.runIt();
		Test.stopTest();
	}
}