src/objects/Visitor__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Number__c</fullName>
        <label>Chat Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>language__c</fullName>
        <label>language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visitor</label>
    <nameField>
        <displayFormat>V{00000000}</displayFormat>
        <label>Visitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FlowSendVideo2.cls
/**
Author:         serhiivolynets
Date:           24.08.2020
Description:   
**/

global class FlowSendVideo2
{

		@AuraEnabled @InvocableVariable public id visitorId;
		@AuraEnabled @InvocableVariable public string fileURL;
		@AuraEnabled @InvocableVariable public string caption;


	@InvocableMethod(label='Send Video' description='sends a Video')
	global static void sendVideo(list<FlowSendVideo2> lParam)
	{
		system.debug('FlowSendVideo.start');
		set<id>sids = new set<id>();
		for(FlowSendVideo2 inp: lParam)
		{
			sids.add((id)inp.visitorId);
		}
		map<id,Visitor__c> mVis = new map<id,Visitor__c>(DM080_Visitor.getRecords(sids));
		for(FlowSendVideo2 inp: lParam)
		{
			Visitor__c vis = mVis.get((id)inp.visitorId);
			if(vis.language__c != 'en' && vis.language__c != null && vis.language__c != '')
				inp.caption = SM010_Utils.translate(inp.caption,vis.language__c);
			SM042_NexmoOut4.sendVideo(vis.Id__c,vis.Chat_Number__c,inp.fileURL, inp.caption);
			SM042_NexmoOut2.pause(800);
		}
	}
}