src/objects/Visitor__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Number__c</fullName>
        <label>Chat Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Livechat_Session_Key__c</fullName>
        <label>Livechat Session Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Visitor</label>
    <nameField>
        <displayFormat>V{00000000}</displayFormat>
        <label>Visitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LiveChatStatusBatchTest.cls
/**
Author:         serhiivolynets
Date:           09.09.2022
Description:   
**/
@IsTest
public with sharing class LiveChatStatusBatchTest
{
	@TestSetup
	public static void prepareData()
	{
		Visitor__c v = SM031_NexmoTEST.createExistingVisitor('Full Access');
		v.Chat_Number__c ='111';
		v.Livechat_Session_Key__c = '111';
		v.Livechat_affinityToken__c = '111';
		update v;
	}

	@IsTest
	public static void testBatch()
	{
		Test.startTest();
		LiveChatStatusBatch.start();
		Test.stopTest();
	}

}